name: LLVM-Tblgen-Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/workflows/LLVM-Auto-Updater.yml"
      - "CONTRIBUTING.md"
      - "README.md"
      - "LICENSE.TXT"
      - "SECURITY.md"
    branches: 
      - auto-sync*
  pull_request:
    paths-ignore:
      - ".github/workflows/LLVM-Auto-Updater.yml"
      - "CONTRIBUTING.md"
      - "README.md"
      - "LICENSE.TXT"
      - "SECURITY.md"
    branches: 
      - auto-sync*
      - release/**

jobs:
  build-llvm-tblgen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout llvm-capstone
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install cmake Ninja

      - name: Build llvm tblgen
        env:
          CC: gcc-12
          CXX: g++-12
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../llvm
          cmake --build . --target llvm-tblgen --config Debug
          cd ..
      - name: Test generated tables
        run: |
          ./compare_tblgen_output.sh
