name: LLVM-Tblgen-Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/workflows/LLVM-Auto-Updater.yml"
      - "CONTRIBUTING.md"
      - "README.md"
      - "LICENSE.TXT"
      - "SECURITY.md"
    branches: 
      - auto-sync*
  pull_request:
    paths-ignore:
      - ".github/workflows/LLVM-Auto-Updater.yml"
      - "CONTRIBUTING.md"
      - "README.md"
      - "LICENSE.TXT"
      - "SECURITY.md"
    branches: 
      - auto-sync*
      - release/**

jobs:
  build-llvm-tblgen:
    runs-on: ubuntu-latest
    steps:
      - uses: lukka/get-cmake@latest
      
      - name: Checkout llvm-capstone
        uses: actions/checkout@v3

      - name: Build llvm tblgen
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../llvm
          cmake --build . --target llvm-tblgen --config Release
          cd ..
      - name: Test generated tables
        run: |
          ./compare_tblgen_output.sh
